apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor-postgres
spec:
  instances: 2
  bootstrap:
    initdb:
      database: registry
      owner: harbor
      secret:
        name: harbor-postgres
  storage:
    size: 5Gi
