apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashy
  namespace: argocd
spec:
  project: isles
  destination:
    server: https://kubernetes.default.svc
    namespace: dashy
  source:
    repoURL: https://github.com/superfishial/isles
    path: dashy
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
