apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: isles
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  source:
    repoURL: https://github.com/superfishial/isles
    path: vaultwarden
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
